version: '3'

services:
  frontend:
    build:
      context: ./websiteTest/websiteAngular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./websiteTest/websiteAngular:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ctem-net

  backend:
    build:
      context: ./website-api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "1337:1337"
    volumes:
      - ./website-api:/app
      - /app/node_modules
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_KEYS: ${APP_KEYS}
    depends_on:
      - db
    networks:
      - ctem-net

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ctem-net

volumes:
  postgres_data:

networks:
  ctem-net:
    name: Ctem
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16
          gateway: 172.50.0.1
